AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: '2.3'
  NewCops: enable
  SuggestExtensions: false

Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 50
Layout/MultilineMethodCallIndentation:
  Enabled: false
