# (The MIT License)
#
# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: '2.3'
  NewCops: enable
  SuggestExtensions: false
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 50
Layout/MultilineMethodCallIndentation:
  Enabled: false
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
