decrypt:
  rubygems.yml: repo/rubygems.yml.asc
release:
  script: |-
    git config --global user.email "test@example.com"
    git config --global user.name "Test"
    ./test.sh
    rm -rf *.gem
    sed -i "s/2.0.snapshot/${tag}/g" jgd.gemspec
    gem build jgd.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
architect:
- yegor256
- yegor256
- davvd