---
name: rake
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rake:
    name: test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        ruby: [2.7, 3.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle update
      - run: bundle exec rake
